import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {BsFillBadgeCcFill} from 'react-icons/bs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Vitor de Lucca Profile </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className=' bg-gradient-to-b from-slate-900 to-gray-800 px-20'>
     <section className='min-h-screen'>
      <nav className='py-16 mb-12 flex justify-between'>
      <a className='flex items-center text-xl font-semibold text-gray-200 tracking-tight hover:text-gray-500 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-150 duration-300' href='#'>
        <span className="flex-initial h-8 w-8 rounded-full mr-3 shadow-md overflow-hidden">
                        <img src='https://i.imgur.com/3p3p2BF.png' alt="Vitor de Lucca photo" width="32px" height="32px"  className=' flex items-center tracking-light' />
        </span>
        Vitor</a>
          <ul className='flex items-center text-gray-300 tracking-light'>
              <li className='transition ease-in-out delay-150 hover:-translate-y-1 hover:-translate-x-3 hover:scale-150 duration-300'>
                <a className='ml-8 hover:text-gray-500 transition ease-in-out delay-150 duration-200' href='#'>Experience</a>
              </li>
              <li className='transition ease-in-out delay-150 hover:-translate-y-1 hover:-translate-x-3 hover:scale-150 duration-300'>
                <a className='ml-8 hover:text-gray-500 transition ease-in-out delay-150 duration-200' href='#'>About</a>
              </li>
          </ul>
      </nav>
     </section>
    </main>
    </>
  )
}
